### PR TITLE
[BREAKING] Fix empty param bag

### LINKED ISSUE #49: Setting `withResourceName` results in an empty ParamBag for Includes.
I'm not yet sure if this issue ultimately rests on `Fractalistic` or the underlying `Fractal` package. Will close if I determine this is the inappropriate place for this issue.  

When `\League\Fractal\TransformerAbstract::callIncludeMethod` calls the `\League\Fractal\Scope::getIdentifier` method the resulting identifier is "incorrect" IF `\Spatie\Fractalistic\Fractal::withResourceName` was called to set a "top level identifier". It's "incorrect" in the sense that `\League\Fractal\Manager::getIncludeParams` method has no entry for the resulting identifier.

 Code example:

url: `/api/v1/abcd/users/36?include=comments:status_in(deleted)`

```
... 
return fractal($user, $transformer, new JsonApiSerializer($base_url))
                ->withResourceName('abcd-users')
                ->respond($status, $headers);
```

Then in `\League\Fractal\TransformerAbstract::callIncludeMethod`

```
protected function callIncludeMethod(Scope $scope, $includeName, $data)
    {
        $scopeIdentifier = $scope->getIdentifier($includeName);
        // resulting `$scopeIdentifer` is `abcd-users.comments`
        $params = $scope->getManager()->getIncludeParams($scopeIdentifier);
        // `$params` is empty as the manager only has `includeParams` for `comments` (not `abcd-users.comments`).
       ... 
} 
```

### LINKED ISSUE #62: Using `withResourceName` makes fractal include parameters not working
**Example:**
```php
$fractal = Fractal::create($users, new UserTransformer())->withResourceName('users');
$fractal->parseIncludes(['posts'])->toArray();
```

In `League\Fractal\TransformerAbstract` at `callIncludeMethod` method we get the following result:
```php
// this line will get 'users.posts' as identifier
$scopeIdentifier = $scope->getIdentifier($includeName);

// this line will try to find include params for 'users.posts' identifier instead 'posts'
$params = $scope->getManager()->getIncludeParams($scopeIdentifier);
```
But **League\Fractal\Scope** object is being built like this:
```
League\Fractal\Scope Object
(
    [availableIncludes:protected] => Array
        (
            [0] => posts
        )
    [scopeIdentifier:protected] => users
    [manager:protected] => League\Fractal\Manager Object
        (
            [requestedIncludes:protected] => Array
                (
                    [0] => posts
                )
            [includeParams:protected] => Array
                (
                    [posts] => Array
                        (
                            [limit] => Array
                                (
                                    [0] => 5,
                                    [1] => 1,
                                )
                        )
                )
```
As you can see `League\Fractal\Manager` will not find the `posts` include params because `getIncludeParams` method will look for `users.posts` key instead.

### PR DESCRIPTION
**Pull request by Mohammad-Alavi**
# Notes
* This PR introduces a **BREAKING CHANGE**.
* ~~This PR is based on #79 and utilizes the test classes introduced there. To make the review process smoother, it’s recommended that this PR be merged after #79.~~

# Summary

This PR addresses #49 and #62, both of which were caused by the changes introduced in #39.

The issue occurs when using the withResourceName method or setting the resource name in any other way, causing the include parameters to be empty. This problem is clearly described in #62.

# More Context

In the use case described in #38, if the data returned by Country differs depending on the context (e.g., in the Portfolio context vs. other contexts), it indicates that a different or new transformer should be used for each context. This is precisely what transformers and includes are designed for: to return different data based on context.

If you need to return different data based on context, it is still possible to do so, as demonstrated in the test case.

resolve #49
resolve #62

### CODE REVIEW

File: tests/TestClasses/CharacterTransformer.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+            'scope_identifier' => $this->getCurrentScope()->getIdentifier(),
+        ];
+
+        if ($parentScope === 'author') {
+            $data['called_by_author'] = 'indeed!';
+        }
+
+        if ($parentScope === 'books') {
+            $data['called_by_book'] = 'yes!';
+        }
```
Comment (Mohammad-Alavi) [inline tests/TestClasses/CharacterTransformer.php:31]: As you can see, we are returnning different fields based on the context that we are in.
In the `author` context we return, `called_by_author` field, and
In the `books` context we return, `called_by_book` field.
It seems this is the reult that #39 wanted to achiev.

File: src/Fractal.php [hunk 2]
```diff
@@ -405,7 +405,7 @@ public function createData()
             $this->manager->parseFieldsets($this->fieldsets);
         }
 
-        return $this->manager->createData($this->getResource(), $this->resourceName);
```
Comment (Mohammad-Alavi) [inline src/Fractal.php:408]: This is the actual fix.
The rest are just tests 😬

**Comment by Mohammad-Alavi** [comment]
Sorry to bother you @Nielsvanpach,
I know you guys are very busy maintaining a lot of packages and I am very grateful for that. 
I just want to know if this PR will be reviewd anytime soon or not.

Thank you 💪

**Comment by freekmurze** [comment]
Since this is a bugfix, I'll release it as such. Thanks!
